Feature passive spieler stimmenueber hinweisab abgeschlossen
adlerhurst/just-one-digital pull request #78
Opened 2021-05-04 16:47 UTC by thurndar

2021-05-05 16:58 UTC, adlerhurst requested changes
e2e tests

2021-05-05 17:45 UTC, adlerhurst commented on backend/JustOneDigital.Tests/GameTests.cs
> +      Assert.AreEqual(GameState.ChooseWord, game.State);
erweitern

2021-05-06 07:56 UTC, thurndar commented on backend/JustOneDigital/Handler/GamePlayerHandler.cs
> +      lobby.Game.OnHintsAccepted();
done

2021-05-06 07:56 UTC, thurndar commented on backend/JustOneDigital/Model/Hint.cs
> +    public void ResetAcceptCounter()
done

2021-05-06 08:32 UTC, thurndar commented on backend/JustOneDigital/Handler/GamePlayerHandler.cs
> +      player.HasVotedForHints = true;
done

2021-05-09 11:56 UTC, adlerhurst approved these changes

2021-05-09 17:59 UTC, merged